services:
    sos.matching:
       class: SosBundle\Service\Matching
       arguments: ["@doctrine.orm.entity_manager"]
    
    sos.user_manipulator:
      class:      SosBundle\Util\UserManipulator
      arguments:  ["@fos_user.user_manager"]